CC = gcc
CFLAGS=-Wall -g
CLIB=-L /usr/lib -lpthread
CINC=-I/usr/include


C_SOURCES =             \
    udp_snd.c

all: $(C_SOURCES)
	$(CC) $(CFLAGS) $(C_SOURCES) $(CLIB) $(CINC) -o udp_snd.exe
#     2>&1 
#    | tee build.log

clean:
	/bin/rm -f *.o udp_snd.exe udp_snd
