CC = gcc
CFLAGS=-Wall -g
CLIB=
CINC = -I../inc

H_SOURCES =			    \
	../inc/viSdefs.h    \
	../inc/viSerror.h   \
	../inc/viSstruct.h

C_SOURCES = 		\
	yuv422planartoyuv422uyvy.c

all: $(C_SOURCES)
	$(CC) $(CFLAGS) $(C_SOURCES) $(CLIBS) $(CINC) -o yuv422planartoyuv422uyvy 2>&1 | tee build.log

clean:
	/bin/rm -f *.o yuv422planartoyuv422uyvy.exe yuv422planartoyuv422uyvy
